on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore
      run: dotnet restore
    
    - name: Build Pushinator.Web
      run: dotnet build --configuration Release
      working-directory: Pushinator.Web
    
    - name: Publish Pushinator.Web
      run: dotnet publish --configuration Release
      working-directory: Pushinator.Web

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Get short SHA
      id: short_sha
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
   
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: Pushinator.Web         
        tags: "takayoshisimizu/pushinator-web:${{ steps.short_sha.outputs.sha8 }}"
